/*
 * Created on 18 dic 2015 ( Time 16:29:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.sinergis.datacatalogue.persistence.services.fake;

import java.util.List;
import java.util.Map;

import it.sinergis.datacatalogue.bean.jpa.Gsc003RoleEntity;
import it.sinergis.datacatalogue.persistence.commons.fake.GenericFakeService;
import it.sinergis.datacatalogue.persistence.services.Gsc003RolePersistence;

/**
 * Fake persistence service implementation ( entity "Gsc003Role" )
 *
 * @author Telosys Tools Generator
 */
public class Gsc003RolePersistenceFAKE extends GenericFakeService<Gsc003RoleEntity> implements Gsc003RolePersistence {

	public Gsc003RolePersistenceFAKE () {
		super(Gsc003RoleEntity.class);
	}
	
	protected Gsc003RoleEntity buildEntity(int index) {
		Gsc003RoleEntity entity = new Gsc003RoleEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setJson( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(Gsc003RoleEntity entity) {
		log("delete ( Gsc003RoleEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(Gsc003RoleEntity entity) {
		log("insert ( Gsc003RoleEntity : " + entity + ")" ) ;
	}

	public Gsc003RoleEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<Gsc003RoleEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<Gsc003RoleEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<Gsc003RoleEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public Gsc003RoleEntity save(Gsc003RoleEntity entity) {
		log("insert ( Gsc003RoleEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<Gsc003RoleEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

	@Override
	public List<Object> loadByNativeQueryGenericObject(String query) {
		return null;
	}

	@Override
	public List<Gsc003RoleEntity> loadByNativeQuery(String query) {
		return null;
	}

}
