/*
 * Created on 18 dic 2015 ( Time 16:29:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.sinergis.datacatalogue.persistence.services.fake;

import java.util.List;
import java.util.Map;

import it.sinergis.datacatalogue.bean.jpa.Gsc002UserEntity;
import it.sinergis.datacatalogue.persistence.commons.fake.GenericFakeService;
import it.sinergis.datacatalogue.persistence.services.Gsc002UserPersistence;

/**
 * Fake persistence service implementation ( entity "Gsc002User" )
 *
 * @author Telosys Tools Generator
 */
public class Gsc002UserPersistenceFAKE extends GenericFakeService<Gsc002UserEntity> implements Gsc002UserPersistence {

	public Gsc002UserPersistenceFAKE () {
		super(Gsc002UserEntity.class);
	}
	
	protected Gsc002UserEntity buildEntity(int index) {
		Gsc002UserEntity entity = new Gsc002UserEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setJson( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(Gsc002UserEntity entity) {
		log("delete ( Gsc002UserEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(Gsc002UserEntity entity) {
		log("insert ( Gsc002UserEntity : " + entity + ")" ) ;
	}

	public Gsc002UserEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<Gsc002UserEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<Gsc002UserEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<Gsc002UserEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public Gsc002UserEntity save(Gsc002UserEntity entity) {
		log("insert ( Gsc002UserEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<Gsc002UserEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
