/*
 * Created on 18 dic 2015 ( Time 16:29:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.sinergis.datacatalogue.persistence.services.fake;

import java.util.List;
import java.util.Map;

import it.sinergis.datacatalogue.bean.jpa.Gsc010ApplicationEntity;
import it.sinergis.datacatalogue.persistence.commons.fake.GenericFakeService;
import it.sinergis.datacatalogue.persistence.services.Gsc010ApplicationPersistence;

/**
 * Fake persistence service implementation ( entity "Gsc010Application" )
 *
 * @author Telosys Tools Generator
 */
public class Gsc010ApplicationPersistenceFAKE extends GenericFakeService<Gsc010ApplicationEntity> implements Gsc010ApplicationPersistence {

	public Gsc010ApplicationPersistenceFAKE () {
		super(Gsc010ApplicationEntity.class);
	}
	
	protected Gsc010ApplicationEntity buildEntity(int index) {
		Gsc010ApplicationEntity entity = new Gsc010ApplicationEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setJson( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(Gsc010ApplicationEntity entity) {
		log("delete ( Gsc010ApplicationEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(Gsc010ApplicationEntity entity) {
		log("insert ( Gsc010ApplicationEntity : " + entity + ")" ) ;
	}

	public Gsc010ApplicationEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<Gsc010ApplicationEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<Gsc010ApplicationEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<Gsc010ApplicationEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public Gsc010ApplicationEntity save(Gsc010ApplicationEntity entity) {
		log("insert ( Gsc010ApplicationEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<Gsc010ApplicationEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
