/*
 * Created on 18 dic 2015 ( Time 16:29:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.sinergis.datacatalogue.persistence.services.fake;

import java.util.List;
import java.util.Map;

import it.sinergis.datacatalogue.bean.jpa.Gsc009GrouplayerEntity;
import it.sinergis.datacatalogue.persistence.commons.fake.GenericFakeService;
import it.sinergis.datacatalogue.persistence.services.Gsc009GrouplayerPersistence;

/**
 * Fake persistence service implementation ( entity "Gsc009Grouplayer" )
 *
 * @author Telosys Tools Generator
 */
public class Gsc009GrouplayerPersistenceFAKE extends GenericFakeService<Gsc009GrouplayerEntity> implements Gsc009GrouplayerPersistence {

	public Gsc009GrouplayerPersistenceFAKE () {
		super(Gsc009GrouplayerEntity.class);
	}
	
	protected Gsc009GrouplayerEntity buildEntity(int index) {
		Gsc009GrouplayerEntity entity = new Gsc009GrouplayerEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setJson( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(Gsc009GrouplayerEntity entity) {
		log("delete ( Gsc009GrouplayerEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(Gsc009GrouplayerEntity entity) {
		log("insert ( Gsc009GrouplayerEntity : " + entity + ")" ) ;
	}

	public Gsc009GrouplayerEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<Gsc009GrouplayerEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<Gsc009GrouplayerEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<Gsc009GrouplayerEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public Gsc009GrouplayerEntity save(Gsc009GrouplayerEntity entity) {
		log("insert ( Gsc009GrouplayerEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<Gsc009GrouplayerEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
