/*
 * Created on 18 dic 2015 ( Time 16:29:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.sinergis.datacatalogue.persistence.services.fake;

import java.util.List;
import java.util.Map;

import it.sinergis.datacatalogue.bean.jpa.Gsc001OrganizationEntity;
import it.sinergis.datacatalogue.persistence.commons.fake.GenericFakeService;
import it.sinergis.datacatalogue.persistence.services.Gsc001OrganizationPersistence;

/**
 * Fake persistence service implementation ( entity "Gsc001Organization" )
 *
 * @author Telosys Tools Generator
 */
public class Gsc001OrganizationPersistenceFAKE extends GenericFakeService<Gsc001OrganizationEntity> implements Gsc001OrganizationPersistence {

	public Gsc001OrganizationPersistenceFAKE () {
		super(Gsc001OrganizationEntity.class);
	}
	
	protected Gsc001OrganizationEntity buildEntity(int index) {
		Gsc001OrganizationEntity entity = new Gsc001OrganizationEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setJson( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(Gsc001OrganizationEntity entity) {
		log("delete ( Gsc001OrganizationEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(Gsc001OrganizationEntity entity) {
		log("insert ( Gsc001OrganizationEntity : " + entity + ")" ) ;
	}

	public Gsc001OrganizationEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<Gsc001OrganizationEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<Gsc001OrganizationEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<Gsc001OrganizationEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public Gsc001OrganizationEntity save(Gsc001OrganizationEntity entity) {
		log("insert ( Gsc001OrganizationEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<Gsc001OrganizationEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

	@Override
	public List<Gsc001OrganizationEntity> getOrganizations(String query) {
		return null;
	}

	@Override
	public List<Object> loadByNativeQueryGenericObject(String query) {
		return null;
	}

}
