/*
 * Created on 18 dic 2015 ( Time 16:29:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.sinergis.datacatalogue.persistence.services.fake;

import java.util.List;
import java.util.Map;

import it.sinergis.datacatalogue.bean.jpa.Gsc004FunctionEntity;
import it.sinergis.datacatalogue.persistence.commons.fake.GenericFakeService;
import it.sinergis.datacatalogue.persistence.services.Gsc004FunctionPersistence;

/**
 * Fake persistence service implementation ( entity "Gsc004Function" )
 *
 * @author Telosys Tools Generator
 */
public class Gsc004FunctionPersistenceFAKE extends GenericFakeService<Gsc004FunctionEntity> implements Gsc004FunctionPersistence {

	public Gsc004FunctionPersistenceFAKE () {
		super(Gsc004FunctionEntity.class);
	}
	
	protected Gsc004FunctionEntity buildEntity(int index) {
		Gsc004FunctionEntity entity = new Gsc004FunctionEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setJson( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(Gsc004FunctionEntity entity) {
		log("delete ( Gsc004FunctionEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(Gsc004FunctionEntity entity) {
		log("insert ( Gsc004FunctionEntity : " + entity + ")" ) ;
	}

	public Gsc004FunctionEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<Gsc004FunctionEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<Gsc004FunctionEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<Gsc004FunctionEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public Gsc004FunctionEntity save(Gsc004FunctionEntity entity) {
		log("insert ( Gsc004FunctionEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<Gsc004FunctionEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
