/*
 * Created on 18 dic 2015 ( Time 16:29:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.sinergis.datacatalogue.persistence.services.fake;

import java.util.List;
import java.util.Map;

import it.sinergis.datacatalogue.bean.jpa.Gsc007DatasetEntity;
import it.sinergis.datacatalogue.persistence.commons.fake.GenericFakeService;
import it.sinergis.datacatalogue.persistence.services.Gsc007DatasetPersistence;

/**
 * Fake persistence service implementation ( entity "Gsc007Dataset" )
 *
 * @author Telosys Tools Generator
 */
public class Gsc007DatasetPersistenceFAKE extends GenericFakeService<Gsc007DatasetEntity> implements Gsc007DatasetPersistence {

	public Gsc007DatasetPersistenceFAKE () {
		super(Gsc007DatasetEntity.class);
	}
	
	protected Gsc007DatasetEntity buildEntity(int index) {
		Gsc007DatasetEntity entity = new Gsc007DatasetEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setJson( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(Gsc007DatasetEntity entity) {
		log("delete ( Gsc007DatasetEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(Gsc007DatasetEntity entity) {
		log("insert ( Gsc007DatasetEntity : " + entity + ")" ) ;
	}

	public Gsc007DatasetEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<Gsc007DatasetEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<Gsc007DatasetEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<Gsc007DatasetEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public Gsc007DatasetEntity save(Gsc007DatasetEntity entity) {
		log("insert ( Gsc007DatasetEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<Gsc007DatasetEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
