/*
 * Created on 18 dic 2015 ( Time 16:29:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.sinergis.datacatalogue.persistence.services.fake;

import java.util.List;
import java.util.Map;

import it.sinergis.datacatalogue.bean.jpa.Gsc006DatasourceEntity;
import it.sinergis.datacatalogue.persistence.commons.fake.GenericFakeService;
import it.sinergis.datacatalogue.persistence.services.Gsc006DatasourcePersistence;

/**
 * Fake persistence service implementation ( entity "Gsc006Datasource" )
 *
 * @author Telosys Tools Generator
 */
public class Gsc006DatasourcePersistenceFAKE extends GenericFakeService<Gsc006DatasourceEntity> implements Gsc006DatasourcePersistence {

	public Gsc006DatasourcePersistenceFAKE () {
		super(Gsc006DatasourceEntity.class);
	}
	
	protected Gsc006DatasourceEntity buildEntity(int index) {
		Gsc006DatasourceEntity entity = new Gsc006DatasourceEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setJson( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(Gsc006DatasourceEntity entity) {
		log("delete ( Gsc006DatasourceEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(Gsc006DatasourceEntity entity) {
		log("insert ( Gsc006DatasourceEntity : " + entity + ")" ) ;
	}

	public Gsc006DatasourceEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<Gsc006DatasourceEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<Gsc006DatasourceEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<Gsc006DatasourceEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public Gsc006DatasourceEntity save(Gsc006DatasourceEntity entity) {
		log("insert ( Gsc006DatasourceEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<Gsc006DatasourceEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
