/*
 * Created on 18 dic 2015 ( Time 16:29:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.sinergis.datacatalogue.persistence.services;

import java.util.List;
import java.util.Map;

import javax.persistence.EntityManager;

import it.sinergis.datacatalogue.bean.jpa.Gsc002UserEntity;
import it.sinergis.datacatalogue.exception.DCException;

/**
 * Basic persistence operations for entity "Gsc002User"
 * 
 * This Bean has a basic Primary Key : Long
 *
 * @author Telosys Tools Generator
 *
 */
public interface Gsc002UserPersistence extends GenericPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param gsc002User
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Gsc002UserEntity gsc002User) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param id
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Long id) ;
	
	/**
	 * Deletes the entity by its Primary Key <br>
	 * no Transactional operation ( no transaction involved )
	 * @param id
	 * @return true if found and deleted, false if not found
	 */
	public boolean deleteNoTrans(Long id,EntityManager em);

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param gsc002User
	 */
	public void insert(Gsc002UserEntity gsc002User) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param id
	 * @return the entity loaded (or null if not found)
	 */
	public Gsc002UserEntity load(Long id) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<Gsc002UserEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<Gsc002UserEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<Gsc002UserEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param gsc002User
	 * @return
	 */
	public Gsc002UserEntity save(Gsc002UserEntity gsc002User) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<Gsc002UserEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
	/**
	 * Load organizations using native query
	 * @param query native query
	 * @return list of organizations
	 */
	public  List<Gsc002UserEntity> getUsers(String query);
	
	/**
	 * Load single organization using native query.
	 * Should be used only if sure there is only 1 record found.
	 * If it finds more than one record error is thrown
	 * 
	 * @param query native query
	 * @return list of organizations
	 */
	public Gsc002UserEntity getUser(String query) throws DCException;
	
	/**
	 * count number of records within a certain id list
	 * @param query native query
	 * @return the count number
	 */
	public Long countInId(String query);
	
}
