/*
 * Created on 18 dic 2015 ( Time 16:29:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.sinergis.datacatalogue.test.persistence;

import org.junit.Assert;
import org.junit.Test;

import it.sinergis.datacatalogue.common.Constants;
import it.sinergis.datacatalogue.services.DatasetsService;
import it.sinergis.datacatalogue.services.DatasourcesService;
import it.sinergis.datacatalogue.services.ServiceCommons;

/**
 * JUnit test case for Gsc007Dataset persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class Gsc007DatasetPersistenceTest extends ServiceCommons {

	final String ID_ORGANIZATION = "28";
	final String CREATE_DATASOURCE_SHAPE = "{\"datasourcename\":\"DSShapeTest\",\"organization\":\"" + ID_ORGANIZATION
			+ "\",\"type\":\"SHAPE\",\"description\":\"SHAPE file\",\"updated\":\"true\",\"path\":\"D:\\\\dati\\\\bologna\\\\shape\\\\\"}";
	
	@Test
	public void testDasetsServiceShape() throws Exception {

		System.out.println("Test datasets service start");

		// For this test we assume the organization exists with the given ID, if
		// it doesn't the test will return success.
		DatasourcesService datasourceDS = new DatasourcesService();
		DatasetsService datasetDS = new DatasetsService();

		String jsonDS = datasourceDS.createDatasource(CREATE_DATASOURCE_SHAPE);
		String idDatasource = getFieldValueFromJsonText(jsonDS, Constants.ID);
		Assert.assertTrue("Datasource created with id: " + idDatasource, idDatasource != null);

		String createDatasetJSON = "{\"datasetname\": \"datasetSHAPETest\",\"realname\": \"zone.shp\",\"iddatasource\":\""
				+ idDatasource + "\",\"description\": \"descrizione\"}";
		String jsonDataset = datasetDS.createDataset(createDatasetJSON);
		Assert.assertTrue(getFieldValueFromJsonText(jsonDataset, Constants.STATUS_FIELD).equalsIgnoreCase(Constants.STATUS_DONE));
		String idDataset = getFieldValueFromJsonText(jsonDataset, Constants.ID);

		Assert.assertTrue("Dataset created with id" + idDataset, idDataset != null);

		String listDatasetJSON = "{\"iddataset\":\"" + idDataset +"\"}";
		datasetDS.listDataset(listDatasetJSON);
		// datasetDS.updateDataset("");
		// datasetDS.listDataset("");
		//
		// datasetDS.listColumns("");
		// datasetDS.updateColumnsMetadata("");
		// datasetDS.listColumns("");
		//
		
		String deleteDatasourceJSON = "{\"iddatasource\":\"" + idDatasource +"\"}";
		String jsonDatasourceDeleted = datasourceDS.deleteDatasource(deleteDatasourceJSON);
		Assert.assertTrue(getFieldValueFromJsonText(jsonDatasourceDeleted, Constants.STATUS_FIELD).equalsIgnoreCase(Constants.STATUS_DONE));

		System.out.println("Test datasets service end");
	}

}
