/*
 * Created on 18 dic 2015 ( Time 16:29:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package it.sinergis.datacatalogue.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import it.sinergis.datacatalogue.bean.jpa.Gsc005PermissionEntity;
import it.sinergis.datacatalogue.persistence.commons.jpa.GenericJpaService;
import it.sinergis.datacatalogue.persistence.commons.jpa.JpaOperation;
import it.sinergis.datacatalogue.persistence.services.Gsc005PermissionPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Gsc005Permission" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class Gsc005PermissionPersistenceJPA extends GenericJpaService<Gsc005PermissionEntity, Long> implements Gsc005PermissionPersistence {

	/**
	 * Constructor
	 */
	public Gsc005PermissionPersistenceJPA() {
		super(Gsc005PermissionEntity.class);
	}

	@Override
	public Gsc005PermissionEntity load( Long id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Long id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(Gsc005PermissionEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("Gsc005PermissionEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
