/*
 * Created on 18 dic 2015 ( Time 16:29:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package it.sinergis.datacatalogue.persistence.services.jpa;


import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import it.sinergis.datacatalogue.bean.jpa.Gsc006DatasourceEntity;
import it.sinergis.datacatalogue.bean.jpa.Gsc007DatasetEntity;
import it.sinergis.datacatalogue.persistence.commons.jpa.GenericJpaService;
import it.sinergis.datacatalogue.persistence.commons.jpa.JpaOperation;
import it.sinergis.datacatalogue.persistence.services.Gsc007DatasetPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Gsc007Dataset" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class Gsc007DatasetPersistenceJPA extends GenericJpaService<Gsc007DatasetEntity, Long> implements Gsc007DatasetPersistence {

	/**
	 * Constructor
	 */
	public Gsc007DatasetPersistenceJPA() {
		super(Gsc007DatasetEntity.class);
	}

	@Override
	public Gsc007DatasetEntity load( Long id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Long id ) {
		return super.delete( id );
	}
	
	@Override
	public boolean deleteNoTrans( Long id, EntityManager em ) {
		final Gsc007DatasetEntity entity = em.find(Gsc007DatasetEntity.class, id);
		if (entity != null) {
			em.remove(entity);
			return Boolean.TRUE ;
		}
		else {
			return Boolean.FALSE ;
		}
	}

	@Override
	public boolean delete(Gsc007DatasetEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("Gsc007DatasetEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}
	
	@Override
	public List<Gsc007DatasetEntity> getDatasets(final String query) {
		return super.loadByNativeQuery(query);
	}

}
