/*
 * Created on 18 dic 2015 ( Time 16:29:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package it.sinergis.datacatalogue.persistence.services.jpa;


import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import it.sinergis.datacatalogue.bean.jpa.Gsc001OrganizationEntity;
import it.sinergis.datacatalogue.persistence.commons.jpa.GenericJpaService;
import it.sinergis.datacatalogue.persistence.commons.jpa.JpaOperation;
import it.sinergis.datacatalogue.persistence.services.Gsc001OrganizationPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Gsc001Organization" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class Gsc001OrganizationPersistenceJPA extends GenericJpaService<Gsc001OrganizationEntity, Long> implements Gsc001OrganizationPersistence {

	/**
	 * Constructor
	 */
	public Gsc001OrganizationPersistenceJPA() {
		super(Gsc001OrganizationEntity.class);
	}

	@Override
	public Gsc001OrganizationEntity load( Long id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Long id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(Gsc001OrganizationEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}
	
	@Override
	public boolean deleteNoTrans( Long id ,EntityManager em) {
		final Gsc001OrganizationEntity entity = em.find(Gsc001OrganizationEntity.class, id);
		if (entity != null) {
			em.remove(entity);
			return Boolean.TRUE ;
		}
		else {
			return Boolean.FALSE ;
		}
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("Gsc001OrganizationEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}
	
	
	@Override
	public List<Gsc001OrganizationEntity> getOrganizations(String query) {
		
		return super.loadByNativeQuery(query);
		
	}
			

}
