/*
 * Created on 18 dic 2015 ( Time 16:29:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package it.sinergis.datacatalogue.persistence.services.jpa;


import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import it.sinergis.datacatalogue.bean.jpa.Gsc006DatasourceEntity;
import it.sinergis.datacatalogue.persistence.commons.jpa.GenericJpaService;
import it.sinergis.datacatalogue.persistence.commons.jpa.JpaOperation;
import it.sinergis.datacatalogue.persistence.services.Gsc006DatasourcePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Gsc006Datasource" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class Gsc006DatasourcePersistenceJPA extends GenericJpaService<Gsc006DatasourceEntity, Long> implements Gsc006DatasourcePersistence {

	/**
	 * Constructor
	 */
	public Gsc006DatasourcePersistenceJPA() {
		super(Gsc006DatasourceEntity.class);
	}

	@Override
	public Gsc006DatasourceEntity load( Long id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Long id ) {
		return super.delete( id );
	}
	
	@Override
	public boolean deleteNoTrans( Long id ,EntityManager em) {
		final Gsc006DatasourceEntity entity = em.find(Gsc006DatasourceEntity.class, id);
		if (entity != null) {
			em.remove(entity);
			return Boolean.TRUE ;
		}
		else {
			return Boolean.FALSE ;
		}
	}

	@Override
	public boolean delete(Gsc006DatasourceEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("Gsc006DatasourceEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

	@Override
	public List<Gsc006DatasourceEntity> getDatasources(String query) {
		
		return super.loadByNativeQuery(query);
		
	}
}
