/*
 * Created on 18 dic 2015 ( Time 16:29:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package it.sinergis.datacatalogue.persistence.services.jpa;


import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import it.sinergis.datacatalogue.bean.jpa.Gsc004FunctionEntity;
import it.sinergis.datacatalogue.bean.jpa.Gsc007DatasetEntity;
import it.sinergis.datacatalogue.persistence.commons.jpa.GenericJpaService;
import it.sinergis.datacatalogue.persistence.commons.jpa.JpaOperation;
import it.sinergis.datacatalogue.persistence.services.Gsc004FunctionPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Gsc004Function" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class Gsc004FunctionPersistenceJPA extends GenericJpaService<Gsc004FunctionEntity, Long> implements Gsc004FunctionPersistence {

	/**
	 * Constructor
	 */
	public Gsc004FunctionPersistenceJPA() {
		super(Gsc004FunctionEntity.class);
	}

	@Override
	public Gsc004FunctionEntity load( Long id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Long id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(Gsc004FunctionEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("Gsc004FunctionEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}
	
	@Override
	public List<Gsc004FunctionEntity> getFunction(final String query) {
		return super.loadByNativeQuery(query);
	}

}
