/*
 * Created on 18 dic 2015 ( Time 16:29:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package it.sinergis.datacatalogue.persistence.services.jpa;


import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import it.sinergis.datacatalogue.bean.jpa.Gsc002UserEntity;
import it.sinergis.datacatalogue.common.Constants;
import it.sinergis.datacatalogue.exception.DCException;
import it.sinergis.datacatalogue.persistence.commons.jpa.GenericJpaService;
import it.sinergis.datacatalogue.persistence.commons.jpa.JpaOperation;
import it.sinergis.datacatalogue.persistence.services.Gsc002UserPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Gsc002User" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class Gsc002UserPersistenceJPA extends GenericJpaService<Gsc002UserEntity, Long> implements Gsc002UserPersistence {

	/**
	 * Constructor
	 */
	public Gsc002UserPersistenceJPA() {
		super(Gsc002UserEntity.class);
	}

	@Override
	public Gsc002UserEntity load( Long id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Long id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(Gsc002UserEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("Gsc002UserEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}
	
	@Override
	public List<Gsc002UserEntity> getUsers(String query) {
		return super.loadByNativeQuery(query);	
	}
	
	@Override
	public Gsc002UserEntity getUser(String query) throws DCException {
		List<Gsc002UserEntity> userList =  super.loadByNativeQuery(query);
		if(userList.size() > 1) {
			DCException ex = new DCException(Constants.ER20);
			throw ex;
		} else if(userList.size() == 0) {
			return null;
		}
		return super.loadByNativeQuery(query).get(0);	
	}

}
