/*
 * Created on 18 dic 2015 ( Time 16:29:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package it.sinergis.datacatalogue.persistence.services.jpa;


import java.math.BigInteger;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import it.sinergis.datacatalogue.bean.jpa.Gsc008LayerEntity;
import it.sinergis.datacatalogue.persistence.PersistenceConfig;
import it.sinergis.datacatalogue.persistence.commons.jpa.GenericJpaService;
import it.sinergis.datacatalogue.persistence.commons.jpa.JpaEnvironment;
import it.sinergis.datacatalogue.persistence.commons.jpa.JpaEnvironments;
import it.sinergis.datacatalogue.persistence.commons.jpa.JpaOperation;
import it.sinergis.datacatalogue.persistence.services.Gsc008LayerPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Gsc008Layer" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class Gsc008LayerPersistenceJPA extends GenericJpaService<Gsc008LayerEntity, Long> implements Gsc008LayerPersistence {

	/**
	 * Constructor
	 */
	public Gsc008LayerPersistenceJPA() {
		super(Gsc008LayerEntity.class);
	}

	@Override
	public Gsc008LayerEntity load( Long id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Long id ) {
		return super.delete( id );
	}
	
	@Override
	public boolean deleteNoTrans( Long id ,EntityManager em) {
		final Gsc008LayerEntity entity = em.find(Gsc008LayerEntity.class, id);
		if (entity != null) {
			em.remove(entity);
			return Boolean.TRUE ;
		}
		else {
			return Boolean.FALSE ;
		}
	}

	@Override
	public boolean delete(Gsc008LayerEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("Gsc008LayerEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}
	
	@Override
	public List<Gsc008LayerEntity> getLayers(String query) {
		
		return super.loadByNativeQuery(query);
		
	}

	@Override
	public Long countInId(String query) {
		EntityManager em = null;
		try {
			JpaEnvironment jpaEnvironment = JpaEnvironments.getInstance().getJpaEnvironment(PersistenceConfig.JPA_PERSISTENCE_UNIT_NAME);
			em = jpaEnvironment.getEntityManagerFactory().createEntityManager();
			Query nativeQuery = em.createNativeQuery(query);					
			return ((BigInteger) nativeQuery.getSingleResult()).longValue();
		} finally {
			// Ensure EntityManager is closed 
			em.close();
		}
	}

}
